DECLARE
  VCOD_RELACIONAMENTO NUMBER;
BEGIN
  VCOD_RELACIONAMENTO := LABDATABASE.PROFISSIONAIS_RESPONSAVEIS_COD_RELACIONAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.PROFISSIONAIS_RESPONSAVEIS VALUES(VCOD_RELACIONAMENTO,
                            '6921345173'
  							'26431888022'
                             );

END;


DECLARE
  VCOD_RELACIONAMENTO NUMBER;
BEGIN
  VCOD_RELACIONAMENTO := LABDATABASE.PROFISSIONAIS_RESPONSAVEIS_COD_RELACIONAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.PROFISSIONAIS_RESPONSAVEIS VALUES(VCOD_RELACIONAMENTO, 
                            '6921345173'
  							'245559105082'  
                             );

END;


DECLARE
  VCOD_RELACIONAMENTO NUMBER;
BEGIN
  VCOD_RELACIONAMENTO := LABDATABASE.PROFISSIONAIS_RESPONSAVEIS_COD_RELACIONAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.PROFISSIONAIS_RESPONSAVEIS VALUES(VCOD_RELACIONAMENTO,  
                            '9231271747'
  							'79816778076' 
                             );

END;



DECLARE
  VCOD_RELACIONAMENTO NUMBER;
BEGIN
  VCOD_RELACIONAMENTO := LABDATABASE.PROFISSIONAIS_RESPONSAVEIS_COD_RELACIONAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.PROFISSIONAIS_RESPONSAVEIS VALUES(VCOD_RELACIONAMENTO,    
                            '6924853679'
  							'31228507023'  
                             );

END;